name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear steps and expected vs actual behavior.
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps or code sample.
  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, versions, etc.
